import { Globe, Mail, Shield, User, Key, Lock, Server, Facebook, Twitter, Instagram, Github, Linkedin, Youtube, Chrome, MessageSquare, Camera, Music, ShoppingCart, CreditCard, Gamepad2, Video, Cloud, Database, Briefcase, GraduationCap, Heart, MapPin, Smartphone, Tv, Headphones, BookOpen, Car, Home, Plane, Coffee, Utensils, ShoppingBag, Palette, Code, Settings, Zap, Layers, Monitor, Wifi, Calendar, Clock, Bell, Flag, Star, Award, Target, TrendingUp, BarChart, PieChart, Activity, Compass, Map, Navigation, Route, Bookmark, Tag, Filter, Search, Edit, Eye, Download, Upload, Share, Copy, Save, Trash, Archive, Folder, File, Image, FileText, MessageCircle, Phone, Webcam, Mic, Speaker, Volume2, Battery, Power, Cpu, HardDrive, MemoryStick as Memory, Network, Bluetooth, Usb, Printer, Scan as Scanner, Mouse, Keyboard, Joystick, RadioIcon, Tv2, Tablet, Watch, Glasses, Shirt, Package, Truck, Building, Store, Factory, School, Hospital, Church, Library, House as Museum, Theater, Radius as Stadium, Sparkle as Park, Bean as Beach, Mountain, Trees as Tree, Flower, Sun, Moon, Cloud as CloudIcon, CloudRain, CloudSnow, Wind, Thermometer, Umbrella, Snowflake, DivideIcon as LucideIcon } from 'lucide-react';

export const iconMap: Record<string, LucideIcon> = {
  globe: Globe,
  mail: Mail,
  shield: Shield,
  user: User,
  key: Key,
  lock: Lock,
  server: Server,
  facebook: Facebook,
  twitter: Twitter,
  instagram: Instagram,
  github: Github,
  linkedin: Linkedin,
  youtube: Youtube,
  chrome: Chrome,
  message: MessageSquare,
  camera: Camera,
  music: Music,
  shopping: ShoppingCart,
  credit: CreditCard,
  game: Gamepad2,
  video: Video,
  cloud: Cloud,
  database: Database,
  briefcase: Briefcase,
  education: GraduationCap,
  heart: Heart,
  location: MapPin,
  phone: Smartphone,
  tv: Tv,
  headphones: Headphones,
  book: BookOpen,
  car: Car,
  home: Home,
  plane: Plane,
  coffee: Coffee,
  food: Utensils,
  bag: ShoppingBag,
  palette: Palette,
  code: Code,
  settings: Settings,
  zap: Zap,
  layers: Layers,
  monitor: Monitor,
  wifi: Wifi,
  calendar: Calendar,
  clock: Clock,
  bell: Bell,
  flag: Flag,
  star: Star,
  award: Award,
  target: Target,
  trending: TrendingUp,
  chart: BarChart,
  pie: PieChart,
  activity: Activity,
  compass: Compass,
  map: Map,
  navigation: Navigation,
  route: Route,
  bookmark: Bookmark,
  tag: Tag,
  filter: Filter,
  search: Search,
  edit: Edit,
  eye: Eye,
  download: Download,
  upload: Upload,
  share: Share,
  copy: Copy,
  save: Save,
  trash: Trash,
  archive: Archive,
  folder: Folder,
  file: File,
  image: Image,
  filetext: FileText,
  messagecircle: MessageCircle,
  phonecall: Phone,
  webcam: Webcam,
  mic: Mic,
  speaker: Speaker,
  volume: Volume2,
  battery: Battery,
  power: Power,
  cpu: Cpu,
  harddrive: HardDrive,
  memory: Memory,
  network: Network,
  bluetooth: Bluetooth,
  usb: Usb,
  printer: Printer,
  scanner: Scanner,
  mouse: Mouse,
  keyboard: Keyboard,
  joystick: Joystick,
  radio: RadioIcon,
  tv2: Tv2,
  tablet: Tablet,
  watch: Watch,
  glasses: Glasses,
  shirt: Shirt,
  package: Package,
  truck: Truck,
  building: Building,
  store: Store,
  factory: Factory,
  school: School,
  hospital: Hospital,
  church: Church,
  library: Library,
  museum: Museum,
  theater: Theater,
  stadium: Stadium,
  park: Park,
  beach: Beach,
  mountain: Mountain,
  tree: Tree,
  flower: Flower,
  sun: Sun,
  moon: Moon,
  cloudicon: CloudIcon,
  cloudrain: CloudRain,
  cloudsnow: CloudSnow,
  wind: Wind,
  thermometer: Thermometer,
  umbrella: Umbrella,
  snowflake: Snowflake,
};

export function getIconComponent(iconName: string): LucideIcon {
  return iconMap[iconName.toLowerCase()] || Globe;
}

export const platformPresets = [
  { name: 'Gmail', icon: 'mail', color: '#ea4335' },
  { name: 'Google', icon: 'chrome', color: '#4285f4' },
  { name: 'Facebook', icon: 'facebook', color: '#1877f2' },
  { name: 'Instagram', icon: 'instagram', color: '#e4405f' },
  { name: 'Twitter', icon: 'twitter', color: '#1da1f2' },
  { name: 'LinkedIn', icon: 'linkedin', color: '#0077b5' },
  { name: 'GitHub', icon: 'github', color: '#333333' },
  { name: 'YouTube', icon: 'youtube', color: '#ff0000' },
  { name: 'WhatsApp', icon: 'message', color: '#25d366' },
  { name: 'PayPal', icon: 'credit', color: '#0070ba' },
  { name: 'Amazon', icon: 'shopping', color: '#ff9900' },
  { name: 'Netflix', icon: 'video', color: '#e50914' },
  { name: 'Spotify', icon: 'music', color: '#1db954' },
  { name: 'Dropbox', icon: 'cloud', color: '#0061ff' },
  { name: 'Slack', icon: 'message', color: '#4a154b' },
  { name: 'Discord', icon: 'message', color: '#5865f2' },
  { name: 'Zoom', icon: 'video', color: '#2d8cff' },
  { name: 'Microsoft', icon: 'settings', color: '#00a1f1' },
  { name: 'Apple', icon: 'smartphone', color: '#007aff' },
  { name: 'Steam', icon: 'game', color: '#171a21' },
  { name: 'Epic Games', icon: 'game', color: '#313131' },
  { name: 'Twitch', icon: 'video', color: '#9146ff' },
  { name: 'Reddit', icon: 'message', color: '#ff4500' },
  { name: 'Pinterest', icon: 'image', color: '#bd081c' },
  { name: 'TikTok', icon: 'video', color: '#000000' },
  { name: 'Snapchat', icon: 'camera', color: '#fffc00' },
  { name: 'Telegram', icon: 'message', color: '#26a5e4' },
  { name: 'Signal', icon: 'message', color: '#3a76f0' },
  { name: 'Uber', icon: 'car', color: '#000000' },
  { name: 'Airbnb', icon: 'home', color: '#ff5a5f' },
  { name: 'Banking', icon: 'building', color: '#1f2937' },
  { name: 'Work Email', icon: 'briefcase', color: '#4f46e5' },
  { name: 'Personal', icon: 'user', color: '#059669' },
  { name: 'Shopping', icon: 'bag', color: '#dc2626' },
  { name: 'Entertainment', icon: 'tv', color: '#7c3aed' },
  { name: 'Education', icon: 'education', color: '#0891b2' },
  { name: 'Health', icon: 'heart', color: '#dc2626' },
  { name: 'Travel', icon: 'plane', color: '#0369a1' },
  { name: 'Food', icon: 'food', color: '#ea580c' },
  { name: 'Photography', icon: 'camera', color: '#7c2d12' },
  { name: 'Design', icon: 'palette', color: '#be185d' },
  { name: 'Development', icon: 'code', color: '#166534' },
  { name: 'Business', icon: 'briefcase', color: '#1f2937' },
  { name: 'Finance', icon: 'trending', color: '#059669' },
];